### ISSUE TITLE
Autobuilder does not seem to calculate weapons with innate multishot properly.

### ISSUE THREAD

**Issue by Roatze** [verystable/warframe-autobuilder#1]
All weapons with innate multishot such as Shotguns seems to calculate multishot on top of their total damage(combined damage of all pellets). This makes some weapons seem to have multiple thousands of base damage without mods.
![Autobuilder](https://user-images.githubusercontent.com/22023647/63642622-3ebc6580-c6c2-11e9-927c-02807e54434f.PNG)

**Comment by verystable** [comment]
Should be fixed. Now Multishot calculation is done using the `Multishot multiplier` instead of Multishot value itself.

**Comment by Roatze** [comment]
Update: Base Damage calculation (and by extension proc dps) still seems to be bugged as it shows multiple thousands of damage compared to the fixed total damage.
![Autobuilder 2 Electric Boogaloo](https://user-images.githubusercontent.com/22023647/64475242-80e4ad00-d180-11e9-9556-8aeeb22f1ed1.PNG)
